from google.cloud import bigquery

SCHEMAS = {
    "orders": [
        bigquery.SchemaField("order_id", "STRING"),
        bigquery.SchemaField("customer_id", "STRING"),
        bigquery.SchemaField("order_status", "STRING"),
        bigquery.SchemaField("order_purchase_timestamp", "TIMESTAMP"),
        bigquery.SchemaField("order_approved_at", "TIMESTAMP"),
        bigquery.SchemaField("order_delivered_carrier_date", "TIMESTAMP"),
        bigquery.SchemaField("order_delivered_customer_date", "TIMESTAMP"),
        bigquery.SchemaField("order_estimated_delivery_date", "TIMESTAMP"),
    ],
    "order_reviews": [
        bigquery.SchemaField("review_id", "STRING"),
        bigquery.SchemaField("order_id", "STRING"),
        bigquery.SchemaField("review_score", "INTEGER"),
        bigquery.SchemaField("review_comment_title", "STRING"),
        bigquery.SchemaField("review_comment_message", "STRING"),
        bigquery.SchemaField("review_creation_date", "TIMESTAMP"),
        bigquery.SchemaField("review_answer_timestamp", "TIMESTAMP"),
    ],
    "order_items": [
        bigquery.SchemaField("order_id", "STRING"),
        bigquery.SchemaField("order_item_id", "INTEGER"),
        bigquery.SchemaField("product_id", "STRING"),
        bigquery.SchemaField("seller_id", "STRING"),
        bigquery.SchemaField("shipping_limit_date", "TIMESTAMP"),
        bigquery.SchemaField("price", "FLOAT"),
        bigquery.SchemaField("freight_value", "FLOAT"),
    ],
    "order_payments": [
        bigquery.SchemaField("order_id", "STRING"),
        bigquery.SchemaField("payment_sequential", "INTEGER"),
        bigquery.SchemaField("payment_type", "STRING"),
        bigquery.SchemaField("payment_installments", "INTEGER"),
        bigquery.SchemaField("payment_value", "FLOAT"),
    ],
    "customers": [
        bigquery.SchemaField("customer_id", "STRING"),
        bigquery.SchemaField("customer_unique_id", "STRING"),
        bigquery.SchemaField("customer_zip_code_prefix", "STRING"),
        bigquery.SchemaField("customer_city", "STRING"),
        bigquery.SchemaField("customer_state", "STRING"),
    ],
    "sellers": [
        bigquery.SchemaField("seller_id", "STRING"),
        bigquery.SchemaField("seller_zip_code_prefix", "STRING"),
        bigquery.SchemaField("seller_city", "STRING"),
        bigquery.SchemaField("seller_state", "STRING"),
    ],
    "products": [
        bigquery.SchemaField("product_id", "STRING"),
        bigquery.SchemaField("product_category_name", "STRING"),
        bigquery.SchemaField("product_name_lenght", "INTEGER"),
        bigquery.SchemaField("product_description_lenght", "INTEGER"),
        bigquery.SchemaField("product_photos_qty", "INTEGER"),
        bigquery.SchemaField("product_weight_g", "FLOAT"),
        bigquery.SchemaField("product_length_cm", "FLOAT"),
        bigquery.SchemaField("product_height_cm", "FLOAT"),
        bigquery.SchemaField("product_width_cm", "FLOAT"),
    ],
    "geolocation": [
        bigquery.SchemaField("geolocation_zip_code_prefix", "STRING"),
        bigquery.SchemaField("geolocation_lat", "FLOAT"),
        bigquery.SchemaField("geolocation_lng", "FLOAT"),
        bigquery.SchemaField("geolocation_city", "STRING"),
        bigquery.SchemaField("geolocation_state", "STRING"),
    ],
    "category_translation": [
        bigquery.SchemaField("product_category_name", "STRING"),
        bigquery.SchemaField("product_category_name_english", "STRING"),
    ],
}