olist:
  target: prod
  outputs:
    prod:
      type: bigquery
      method: service-account
      project: clear-variety-492200-n0
      dataset: olist
      keyfile: "{{ env_var('GCP_KEY_PATH') }}"  # Dynamic path
      location: us-east1
      threads: 4
      timeout_seconds: 300